Rename cortex to corto

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,28 +2,28 @@
 
 VERSION="0.2.0-alpha"
 
-install_cortex_fail() {
-    >&2 echo "cortex: installation failed :("
+install_corto_fail() {
+    >&2 echo "corto: installation failed :("
     rm -rf "$INSTALL_TMPDIR"
-    sudo rm -f "/usr/bin/cortex"
-    sudo rm -f "/usr/bin/cortex.$VERSION"
-    sudo rm -f "/usr/lib/libcortex.so"
-    sudo rm -f "/usr/lib/libcortex.so.$VERSION"
-    sudo rm -rf "/usr/lib/cortex/$VERSION"
-    sudo rm -rf "/usr/include/cortex/$VERSION"
-    sudo rm -rf "$HOME/.cortex"
+    sudo rm -f "/usr/bin/corto"
+    sudo rm -f "/usr/bin/corto.$VERSION"
+    sudo rm -f "/usr/lib/libcorto.so"
+    sudo rm -f "/usr/lib/libcorto.so.$VERSION"
+    sudo rm -rf "/usr/lib/corto/$VERSION"
+    sudo rm -rf "/usr/include/corto/$VERSION"
+    sudo rm -rf "$HOME/.corto"
 }
 
-install_cortex () {
+install_corto () {
     set -e
     set -u
 
     UNAME=$(uname)
     ARCHITECTURE=$(uname -p)
     PREFIX="/usr"
-    FILENAME="cortex"
-    TARBALL_URL="https://s3.amazonaws.com/cortexbinaries/$FILENAME.$UNAME.$ARCHITECTURE.tar.gz"
-    INSTALL_TMPDIR="$HOME/.cortex/.download"
+    FILENAME="corto"
+    TARBALL_URL="https://s3.amazonaws.com/cortobinaries/$FILENAME.$UNAME.$ARCHITECTURE.tar.gz"
+    INSTALL_TMPDIR="$HOME/.corto/.download"
 
     echo
     echo "Hi! Stand by, this will just take a second..."
@@ -31,25 +31,25 @@ install_cortex () {
 
     # Check supported OS
     if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
-        >&2 echo "cortex: sorry, this OS is not supported yet!"
+        >&2 echo "corto: sorry, this OS is not supported yet!"
         exit 1
     fi
     if [ "$UNAME" = "Darwin" ] ; then
         if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
-          >&2 echo "cortex: only 64-bit Intel processors are supported at this time!"
+          >&2 echo "corto: only 64-bit Intel processors are supported at this time!"
           exit 1
         fi
     fi
 
-    trap install_cortex_fail EXIT
+    trap install_corto_fail EXIT
 
     # Ask for password upfront
     sudo true
 
-    # Remove existing version
+    # Remove existing cortex version
     if [ "`which cortex`" != "" ]  ; then
         OLD_VERSION=`cortex -v`
-        echo "cortex: removing your existing cortex distribution ($OLD_VERSION)"
+        echo "corto: removing your existing cortex distribution ($OLD_VERSION)"
         sudo rm -f "/usr/bin/cortex"
         sudo rm -f "/usr/bin/cortex.$OLD_VERSION"
         sudo rm -f "/usr/lib/libcortex.so"
@@ -58,35 +58,47 @@ install_cortex () {
         sudo rm -rf "/usr/include/cortex/$OLD_VERSION"
     fi
 
-    mkdir -p "$HOME/.cortex"
-    sudo mkdir -p "$PREFIX/lib/cortex/$VERSION"
+    # Remove existing version
+    if [ "`which corto`" != "" ]  ; then
+        OLD_VERSION=`corto -v`
+        echo "corto: removing your existing corto distribution ($OLD_VERSION)"
+        sudo rm -f "/usr/bin/corto"
+        sudo rm -f "/usr/bin/corto.$OLD_VERSION"
+        sudo rm -f "/usr/lib/libcorto.so"
+        sudo rm -f "/usr/lib/libcorto.so.$OLD_VERSION"
+        sudo rm -rf "/usr/lib/corto/$OLD_VERSION"
+        sudo rm -rf "/usr/include/corto/$OLD_VERSION"
+    fi
 
-    echo "cortex: downloading distribution"
+    mkdir -p "$HOME/.corto"
+    sudo mkdir -p "$PREFIX/lib/corto/$VERSION"
+
+    echo "corto: downloading distribution"
     rm -rf "$INSTALL_TMPDIR"
     mkdir -p "$INSTALL_TMPDIR"
 
     sudo curl --progress-bar --fail "$TARBALL_URL" | tar -xzf - -C "$INSTALL_TMPDIR"
 
-    echo "cortex: installing files"
+    echo "corto: installing files"
     sudo cp -a "$INSTALL_TMPDIR/." "/usr"
     rm -rf "$INSTALL_TMPDIR"
-    sudo mv "/usr/bin/cortex" "/usr/bin/cortex.$VERSION"
-    sudo mv "/usr/lib/libcortex.so" "/usr/lib/libcortex.so.$VERSION"
-    sudo ln -s "/usr/bin/cortex.$VERSION" "/usr/bin/cortex"
-    sudo ln -s "/usr/lib/libcortex.so.$VERSION" "/usr/lib/libcortex.so"
-    echo "cortex: done!"
+    sudo mv "/usr/bin/corto" "/usr/bin/corto.$VERSION"
+    sudo mv "/usr/lib/libcorto.so" "/usr/lib/libcorto.so.$VERSION"
+    sudo ln -s "/usr/bin/corto.$VERSION" "/usr/bin/corto"
+    sudo ln -s "/usr/lib/libcorto.so.$VERSION" "/usr/lib/libcorto.so"
+    echo "corto: done!"
     echo
 
-    echo "Yay! Cortex $VERSION successfully installed!"
+    echo "Yay! Corto $VERSION successfully installed!"
     echo
     echo "Hit the ground running with:"
     echo
-    echo "   $ cortex create myApp"
+    echo "   $ corto create myApp"
     echo "   $ cd myApp"
-    echo "   $ cortex run"
+    echo "   $ corto run"
     echo
 
     trap - EXIT
 }
 
-install_cortex
+install_corto
