Add `set -eu` to all scripts

diff --git a/install-release-src b/install-release-src
--- a/install-release-src
+++ b/install-release-src
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+set -eu
+
 install_corto_fail() {
     echo "Installation failed :("
 }
@@ -17,8 +20,6 @@ clone_repo() {
 }
 
 install_corto () {
-    set -u
-
     UNAME=$(uname)
     ARCHITECTURE=$(uname -m)
     INSTALL_TMPDIR="$HOME/corto/src"
@@ -38,8 +39,7 @@ install_corto () {
     if [ "$UNAME" = "Linux" ] ; then
         sudo apt-get -y install git build-essential libffi-dev libxml2-dev flex bison libcurl4-openssl-dev libssl-dev
     elif [ "$UNAME" = "Darwin" ] ; then
-        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
-        rc=$?; if [ $rc != 0 ]; then
+        if ! pkgutil --pkg-info=com.apple.pkg.CLTools_Executables; then
             echo "Looks like Xcode command-line tools are not installed. Run:"
             echo "  sudo xcode-select --install"
             echo
@@ -53,9 +53,7 @@ install_corto () {
     echo "Installing corto, this should just take a minute..."
 
     # Remove existing (older) versions
-    corto --version
-    rc=$?
-    if [ $rc -eq 0 ]; then
+    if corto --version; then
         echo ">> Removing existing corto installation, may require your password! <<"
         sudo rm -rf ~/.corto/bin ~/.corto/lib ~/.corto/etc ~/.bake
         sudo rm -rf ~/corto/bin ~/corto/lib ~/corto/etc
@@ -127,8 +125,8 @@ install_corto () {
     echo
     echo "You have installed a release version. This means that corto has been"
     echo "built with optimizations to run as fast as possible, awesome! The downside"
-    echo "is that it is harder to debug, as certain features to spot errors
-    echo "early on are disabled. We recommend to use a debug version when you
+    echo "is that it is harder to debug, as certain features to spot errors"
+    echo "early on are disabled. We recommend to use a debug version when you"
     echo "develop corto apps. To install a dev version from source, do:"
     echo "   $ curl https://corto.io/install-dev-src | sh"
     echo
